// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/health": {
            "get": {
                "description": "返回服务健康状态",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "健康检查",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.HealthResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/http/data": {
            "get": {
                "description": "返回随机数据流，供下载测速使用。size 参数支持 K/M/G 后缀",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "http"
                ],
                "summary": "HTTP 测速数据端点",
                "parameters": [
                    {
                        "type": "string",
                        "default": "10M",
                        "description": "数据大小",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    }
                }
            }
        },
        "/api/v1/http/run": {
            "post": {
                "description": "通过 HTTP(S) 下载/上传测试网络吞吐量，可选通过 SOCKS5 代理",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "http"
                ],
                "summary": "执行 HTTP 测速",
                "parameters": [
                    {
                        "description": "HTTP 测速请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.HttpTestRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.HttpTestResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.SimpleResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/http/upload": {
            "post": {
                "description": "接收上传数据并丢弃，用于上传测速服务端",
                "consumes": [
                    "application/octet-stream"
                ],
                "tags": [
                    "http"
                ],
                "summary": "HTTP 上传端点",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.SimpleResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/iperf/run": {
            "post": {
                "description": "根据请求参数执行 iperf3 客户端或服务端测速",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "iperf"
                ],
                "summary": "执行一次 iperf3 测速",
                "parameters": [
                    {
                        "description": "iperf3 执行请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.IperfRunRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.IperfRunResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.SimpleResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/iperf/server/start": {
            "post": {
                "description": "在当前后端启动 iperf3 服务端 (后台运行)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "iperf"
                ],
                "summary": "启动 iperf3 服务端",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 5201,
                        "description": "监听端口",
                        "name": "port",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.ServerStartResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.SimpleResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/iperf/server/stop": {
            "post": {
                "description": "停止当前后端运行的 iperf3 服务端",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "iperf"
                ],
                "summary": "停止 iperf3 服务端",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.SimpleResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.SimpleResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/iperf/status": {
            "get": {
                "description": "获取当前后端 iperf3 服务端运行状态",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "iperf"
                ],
                "summary": "获取 iperf3 服务端状态",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.ServerStatusResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.HealthResponse": {
            "description": "健康检查响应",
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "model.HttpTestData": {
            "description": "HTTP 测速结果数据",
            "type": "object",
            "properties": {
                "bitrate_bps": {
                    "type": "number",
                    "example": 95000000
                },
                "bytes_total": {
                    "type": "integer",
                    "example": 104857600
                },
                "direction": {
                    "type": "string"
                },
                "duration_sec": {
                    "type": "number",
                    "example": 10
                },
                "error": {
                    "type": "string"
                },
                "finished_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "example": "uuid"
                },
                "proxy": {
                    "type": "string"
                },
                "started_at": {
                    "type": "string"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "running",
                        "completed",
                        "error"
                    ],
                    "example": "completed"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "model.HttpTestRequest": {
            "description": "HTTP 测速请求",
            "type": "object",
            "required": [
                "direction",
                "url"
            ],
            "properties": {
                "direction": {
                    "description": "download 或 upload",
                    "type": "string",
                    "enum": [
                        "download",
                        "upload"
                    ],
                    "example": "download"
                },
                "duration": {
                    "description": "测试时长秒数",
                    "type": "integer",
                    "default": 10,
                    "example": 10
                },
                "insecure": {
                    "description": "跳过 TLS 证书验证",
                    "type": "boolean",
                    "example": false
                },
                "proxy": {
                    "description": "SOCKS5 代理地址 (可选)",
                    "type": "string",
                    "example": "socks5://proxy:1080"
                },
                "url": {
                    "description": "目标 URL",
                    "type": "string",
                    "example": "https://10.0.0.2:8443/api/v1/http/data?size=100M"
                }
            }
        },
        "model.HttpTestResponse": {
            "description": "HTTP 测速响应",
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 0
                },
                "data": {
                    "$ref": "#/definitions/model.HttpTestData"
                },
                "message": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "model.IperfArgs": {
            "description": "iperf3 运行参数",
            "type": "object",
            "properties": {
                "bandwidth": {
                    "description": "带宽限制",
                    "type": "string",
                    "example": "100M"
                },
                "duration": {
                    "description": "测试时长秒数",
                    "type": "integer",
                    "default": 10,
                    "example": 10
                },
                "extra": {
                    "description": "额外命令行参数",
                    "type": "string"
                },
                "parallel": {
                    "description": "并行流数",
                    "type": "integer",
                    "default": 1,
                    "example": 1
                },
                "port": {
                    "description": "端口",
                    "type": "integer",
                    "default": 5201,
                    "example": 5201
                },
                "protocol": {
                    "description": "tcp 或 udp",
                    "type": "string",
                    "enum": [
                        "tcp",
                        "udp"
                    ],
                    "example": "tcp"
                },
                "reverse": {
                    "description": "反向测试",
                    "type": "boolean",
                    "example": false
                },
                "target": {
                    "description": "客户端模式必填: 目标服务器 IP",
                    "type": "string",
                    "example": "10.0.0.2"
                }
            }
        },
        "model.IperfRunData": {
            "description": "iperf3 执行结果数据",
            "type": "object",
            "properties": {
                "command": {
                    "type": "string",
                    "example": "iperf3 -c 10.0.0.2 -p 5201 -t 10 -J"
                },
                "finished_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "example": "uuid"
                },
                "output": {
                    "type": "string"
                },
                "started_at": {
                    "type": "string"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "running",
                        "completed",
                        "error"
                    ],
                    "example": "completed"
                },
                "summary": {
                    "$ref": "#/definitions/model.IperfSummary"
                }
            }
        },
        "model.IperfRunRequest": {
            "description": "iperf3 执行请求",
            "type": "object",
            "required": [
                "args",
                "mode"
            ],
            "properties": {
                "args": {
                    "$ref": "#/definitions/model.IperfArgs"
                },
                "mode": {
                    "description": "client 或 server",
                    "type": "string",
                    "enum": [
                        "client",
                        "server"
                    ],
                    "example": "client"
                }
            }
        },
        "model.IperfRunResponse": {
            "description": "iperf3 执行结果",
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 0
                },
                "data": {
                    "$ref": "#/definitions/model.IperfRunData"
                },
                "message": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "model.IperfSummary": {
            "description": "iperf3 结果摘要",
            "type": "object",
            "properties": {
                "bitrate_bps": {
                    "type": "number",
                    "example": 945000000
                },
                "duration_sec": {
                    "type": "number",
                    "example": 10
                },
                "jitter_ms": {
                    "type": "number",
                    "example": 0.5
                },
                "lost_percent": {
                    "type": "number",
                    "example": 0
                }
            }
        },
        "model.ServerStartData": {
            "description": "iperf3 server 启动数据",
            "type": "object",
            "properties": {
                "pid": {
                    "type": "integer",
                    "example": 12345
                },
                "port": {
                    "type": "integer",
                    "example": 5201
                }
            }
        },
        "model.ServerStartResponse": {
            "description": "iperf3 server 启动响应",
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 0
                },
                "data": {
                    "$ref": "#/definitions/model.ServerStartData"
                },
                "message": {
                    "type": "string",
                    "example": "server started"
                }
            }
        },
        "model.ServerStatusData": {
            "description": "iperf3 server 状态数据",
            "type": "object",
            "properties": {
                "pid": {
                    "type": "integer",
                    "example": 12345
                },
                "port": {
                    "type": "integer",
                    "example": 5201
                },
                "running": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "model.ServerStatusResponse": {
            "description": "iperf3 server 状态响应",
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 0
                },
                "data": {
                    "$ref": "#/definitions/model.ServerStatusData"
                },
                "message": {
                    "type": "string",
                    "example": "server running"
                }
            }
        },
        "model.SimpleResponse": {
            "description": "通用响应",
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 0
                },
                "message": {
                    "type": "string",
                    "example": "ok"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "iperf-rpc API",
	Description:      "基于 iperf3 的网络测速 RPC 服务",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
